site_name: yuan's Blog
copyright: Ro Shimmmfan | © 2025 | All rights reserved.
theme: 
  name: material

  language: zh

  features:
    - navigation.footer #文章切换脚标
    - navigation.top # 返回顶部按钮
    - search.highlight # 搜索结果高亮
    - navigation.tabs # 分类标签
    - toc.follow # 锚点跟随
    - navigation.instant
    - navigation.instant.progress # 加载进度指示器
  
     
  logo: yuanBlogLogo.png
  favicon: yuanBlogLogoInverted.png

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch
        name: 白昼模式

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: cyan
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 暗夜模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: 根据系统


nav: 
  - "Welcome": index.md
  - "技术":
    - tech/index.md
    - "硬件":
      - "将USB网络共享至小米路由器3": tech/MIR3.md
    - "软件":
      - "从零开始在Win11部署Material for MkDocs": tech/MKDocs.md